export interface OrganizationApplicationModel {
    "certificateType":  String,
    "certificateClass": String,
    "certificateValidityYears": number,
    "houseNumber": String,
    "streetAddress": String,
    "city": String,
    "postCode": String,
    "district": String,
    "country": String,
    "orgType": String,
    "orgName": String,
    "applicantDesignation": String,
    "applicantDepartment": String,
    "orgHouseNumber": String,
    "orgStreetAddress": String,
    "orgCity": String,
    "orgEmail": String,
    "orgPostCode": String,
    "orgDistrict": String,
    "orgCountry": String,
    "orgPhoneNumber": String,
    "document3Id": String,
    "document2Id": String,
    "document1Id": String,
    "utilityBillType": String,
    "document4Id": String,
    "document5Id":String,
    "document6Id": String,
    "document7Id": String,
    "document8Id": String
}